[tool.poetry]
name = "rag-assistant"
version = "0.1.0"
description = "Modular RAG assistant for legal brief analysis"
authors = ["Getahune Alemayhu getahune.alemayhu@gmail.com"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
python-dotenv = "^1.1.1"
